### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by riramar** [3xp10it/bypass_waf#17]
```
python3 xwaf.py -u "https://[some domain]/[some path]?q=xpto"
Requirement already up-to-date: exp10it in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: bs4 in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: chardet in /usr/lib/python3/dist-packages (from exp10it)
Requirement already up-to-date: colorama in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: configparser in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: mechanicalsoup in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: pycrypto in /usr/lib/python3/dist-packages (from exp10it)
Requirement already up-to-date: pymysql in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: readline in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: requests in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: selenium in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: wget in /usr/local/lib/python3.6/dist-packages (from exp10it)
Requirement already up-to-date: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from bs4->exp10it)
Requirement already up-to-date: six>=1.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it)
Requirement already up-to-date: lxml in /usr/local/lib/python3.6/dist-packages (from mechanicalsoup->exp10it)
Requirement already up-to-date: cryptography in /usr/local/lib/python3.6/dist-packages (from pymysql->exp10it)
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->exp10it)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->exp10it)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->exp10it)
Requirement already up-to-date: cffi!=1.11.3,>=1.7 in /usr/local/lib/python3.6/dist-packages (from cryptography->pymysql->exp10it)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/lib/python3/dist-packages (from cryptography->pymysql->exp10it)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.7->cryptography->pymysql->exp10it)
                      __ 
                     / _|
__  ____      ____ _| |_ 
\ \/ /\ \ /\ / / _` |  _|
 >  <  \ V  V / (_| | |  
/_/\_\  \_/\_/ \__,_|_|  
                         
                         
currentVersion:1.18
Do you want to use random proxy from the Internet on each different sqlmap command to anti blocked by waf for your mass requests? [N|y]
4 seconds left...please input your chioce:>n
you choosed n
3 seconds left...please input your chioce:>Traceback (most recent call last):
  File "xwaf.py", line 2843, in <module>
    Program()
  File "xwaf.py", line 76, in __init__
    self.check_DB_type_from_script(each_script)
  File "xwaf.py", line 421, in check_DB_type_from_script
    tamper_content = f.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

**Comment by 3xp10it** [comment]
`https://[some domain]/[some path]?q=xpto`
这句http请求返回的html代码里的非ascii字符有哪些，粘上来我调试下

**Comment by riramar** [comment]
AFAIK there is no non-ascii chars. Find below the curl -v response output.

```
< HTTP/2 401 
< date: Mon, 17 Dec 2018 11:36:48 GMT
< content-type: application/json
< content-length: 36
< set-cookie: __cfduid=[cookie]; expires=Tue, 17-Dec-19 11:36:47 GMT; path=/; domain=.[some domain]; HttpOnly; Secure
< strict-transport-security: max-age=0; includeSubDomains
< vary: Origin
< x-content-type-options: nosniff
< x-ratelimit-limit: 600
< x-ratelimit-remaining: 598
< x-ratelimit-reset: 2018-12-17T11:37:00Z
< x-request-id: [random]
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: [random]
< 
{"error":"Bad authentication error"}
```

**Comment by 3xp10it** [comment]
The issue should be from a sqlmap tamper script file which has non-ascii chars,I have update xwaf.py to ignore the open non-ascii errors,you can directly run the former command again to check it.

**Comment by riramar** [comment]
It worked! Thanks!
