### ISSUE TITLE
一直重复安裝步骤...

### ISSUE THREAD

**Issue by huitc** [3xp10it/bypass_waf#18]
`xxxxx@DESKTOP-X0X00XX:~/bypass_waf$ python3 xwaf.py -u "http://www.baidu.com/1.php?id=1"`
```
Collecting exp10it
  Downloading https://files.pythonhosted.org/packages/33/11/6598105aaa3ec704d7e54acb2a83624abf8141637e727802d1ef1700939c/exp10it-2.6.97.tar.gz (181kB)
    100% |████████████████████████████████| 184kB 44.1MB/s
Collecting bs4 (from exp10it)
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting chardet (from exp10it)
...
```
usage要求装的都装上了 但...
windows store版kali

还有windows上能用么
`--update`能跟上[sqlmap](https://github.com/sqlmapproject/sqlmap)么

(小白

**Comment by huitc** [comment]
@3xp10it

**Comment by 3xp10it** [comment]
#### 一直重复安装步骤的原因

第11行有句：
`os.system("pip3 install exp10it -U --no-cache-dir")`
这句用于每次运行时自动更新exp10it模块(这个模块更新比较多），如果不需要经常保持最新可将这行代码注释成:
`#os.system("pip3 install exp10it -U --no-cache-dir")`

#### windows上能用么

最好用原版的kali，windows不保证可运行

#### `--update`能跟上sqlmap么

`xwaf`自身不带`--upadate`的选项，如果`sqlmap`有`--update` 的选项则`xwaf`支持通过`python3 xwaf.py --update`来更新sqlmap

**Comment by huitc** [comment]
能不能额外弄一个选项 比如: `--xwaf-update`来更方便的进行更新
还有`termux`支持么？
一定要用`kali linux`? 其他的不可以？
之后会支持windows 直接`python2 xwaf.py`么

**Comment by huitc** [comment]
`xxxxx@DESKTOP-X0X00XX:~/waf$ sudo python3 xwaf.py -v 2 --update`
```
    ============ Building the readline extension module ============

    running install
    running build
    running build_ext
    building 'readline' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/Modules
    creating build/temp.linux-x86_64-3.6/Modules/3.x
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python3.6m -c Modules/3.x/readline.c -o build/temp.linux-x86_64-3.6/Modules/3.x/readline.o -Wno-strict-prototypes
    Modules/3.x/readline.c: In function ‘PyInit_readline’:
    Modules/3.x/readline.c:1179:34: warning: assignment to ‘char * (*)(FILE *, FILE *, const char *)’ {aka ‘char * (*)(struct _IO_FILE *, struct _IO_FILE *, const char *)’} from incompatible pointer type ‘char * (*)(FILE *, FILE *, char *)’ {aka ‘char * (*)(struct _IO_FILE *, struct _IO_FILE *, char *)’} [-Wincompatible-pointer-types]
         PyOS_ReadlineFunctionPointer = call_readline;
                                      ^
    creating build/lib.linux-x86_64-3.6
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/Modules/3.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-3.6/readline.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xrso89k_/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wrreskzh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xrso89k_/readline/
Traceback (most recent call last):
  File "xwaf.py", line 12, in <module>
    from exp10it import figlet2file
ModuleNotFoundError: No module named 'exp10it'
```
`xxxxx@DESKTOP-X0X00XX:~/waf$ `

**Comment by 3xp10it** [comment]
1、目前只支持python3+kali linux，其他环境下暂不支持，后续如果有空可以考虑添加支持更多系统
2、从上面你的日志来看，应该是exp10it模块没有安装成功，需要先安装exp10it模块，也即`pip3 install exp10it`,只有安装了exp10it之后才能正常运行

**Comment by huitc** [comment]
xxxxx@DESKTOP-X0X00XX:~/waf$ sudo python3 xwaf.py -v 2 --update
```
Cloning into '/usr/share/sqlmap'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 64078 (delta 26), reused 27 (delta 13), pack-reused 64034
Receiving objects: 100% (64078/64078), 61.37 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (50253/50253), done.
Attention! New version exists,I will update xwaf.py to the latest version.
Update finished! :)
/usr/bin/python3: can't find '__main__' module in '/home/huitc/waf/'
```
xxxxx@DESKTOP-X0X00XX:~/waf$

**Comment by 3xp10it** [comment]
从上面报错看是readline模块没安装成功

**Comment by 3xp10it** [comment]
后续有时间会考虑这个

**Comment by huitc** [comment]
termux[https://play.google.com/store/apps/details?id=com.termux](url) can't install exp10it...
```
python3 -m pip install exp10it -U --no-cache-dir
Collecting exp10it
  Downloading https://files.pythonhosted.org/packages/c9/5f/c544b6215365fce6bd71a4390f7fc69e8e6a51850d91a59c70ac62c04354/exp10it-2.7.16.tar.gz (180kB)
    100% |████████████████████████████████| 184kB 7.0MB/s
    Complete output from command python setup.py egg_info:
    sh: can't create /tmp/exp10it_setup: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-rvx8sncu/exp10it/setup.py", line 42, in <module>
        with open("/tmp/exp10it_setup", "r+") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/exp10it_setup'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-rvx8sncu/exp10it/
```

**Comment by 3xp10it** [comment]
从报错看应该是系统没有/tmp目录导致

**Comment by huitc** [comment]
.
ok....
