### ISSUE TITLE
请问运行出现这个报错  如何解？

### ISSUE THREAD

**Issue by wangyan-samuel** [3xp10it/bypass_waf#31]
Traceback (most recent call last):
  File "/usr/local/src/xwaf/xwaf.py", line 2846, in <module>
    Program()
  File "/usr/local/src/xwaf/xwaf.py", line 33, in __init__
    self.selfUpdate()
  File "/usr/local/src/xwaf/xwaf.py", line 181, in selfUpdate
    latestVersion=getVersion("/tmp/xwaf.py")
  File "/usr/local/src/xwaf/xwaf.py", line 176, in getVersion
    latestVersion=re.search(r"self\.currentVersion\s*=\s*(.*)",content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by solomanhl** [comment]
跟你一样 ，环境kali   python3.10.8
