### ISSUE TITLE
exp10it-2.4.80报错

### ISSUE THREAD

**Issue by gitfuzzing** [3xp10it/bypass_waf#5]
root@kali:~/exp10it-2.4.80# python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing exp10it.egg-info/PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    py_modules=['exp10it','updateapi'],
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.6-py3.4.egg/setuptools/command/install.py", line 67, in run
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.6-py3.4.egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.6-py3.4.egg/setuptools/command/bdist_egg.py", line 152, in run
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.6-py3.4.egg/setuptools/command/egg_info.py", line 179, in run
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.6-py3.4.egg/setuptools/command/egg_info.py", line 390, in write_pkg_info
  File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
    lines = header.split('\n')
TypeError: Type str doesn't support the buffer API

**Comment by 3xp10it** [comment]
有没有试过：pip3 install exp10it
