### ISSUE TITLE
centos下报错

### ISSUE THREAD

**Issue by cnwpdb** [3xp10it/bypass_waf#7]
Requirement already up-to-date: exp10it in /usr/local/lib/python3.6/site-packages

/bin/sh: figlet: 未找到命令
sh: apt-get: 未找到命令
/bin/sh: figlet: 未找到命令
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/exp10it.py", line 1140, in figlet2file
    figlet_font_dir = all[0][:-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xwaf.py", line 2840, in <module>
    Program()
  File "xwaf.py", line 40, in __init__
    figlet2file("xwaf", 0, True)
  File "/usr/local/lib/python3.6/site-packages/exp10it.py", line 1147, in figlet2file
    figlet_font_dir = all[0][:-1]
IndexError: list index out of range

请问 /usr/local/lib/python3.6/site-packages/exp10it.py  这里的 apt-get 是否要替换成 yum  ?

**Comment by 3xp10it** [comment]
最好用基于debian的系统[ubuntu|kali],由于未在centos上测试,只换成yum不确定会不会有其他问题.
