### ISSUE TITLE
No module named 'exp10it'

### ISSUE THREAD

**Issue by avir4er** [3xp10it/bypass_waf#8]
root@localhost:/home/bypass_waf# python3 xwaf.py

Usage:
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-cache
Traceback (most recent call last):
  File "xwaf.py", line 12, in <module>
    from exp10it import figlet2file
ImportError: No module named 'exp10it'
root@localhost:/home/bypass_waf# pip3 install exp10it
Downloading/unpacking exp10it
  Downloading exp10it-2.6.12.tar.gz (993kB): 993kB downloaded
  Running setup.py (path:/tmp/pip-build-x0iek_d8/exp10it/setup.py) egg_info for package exp10it
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-x0iek_d8/exp10it/setup.py", line 54, in <module>
        py_modules=['exp10it','updateapi'],
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 14, in replacement_run
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 349, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/exp10it.egg-info

writing top-level names to pip-egg-info/exp10it.egg-info/top_level.txt

writing pip-egg-info/exp10it.egg-info/PKG-INFO

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-x0iek_d8/exp10it/setup.py", line 54, in <module>

    py_modules=['exp10it','updateapi'],

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "<string>", line 14, in replacement_run

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 349, in write_pkg_info

    metadata.write_pkg_info(cmd.egg_info)

  File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info

    self.write_pkg_file(pkg_info)

  File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file

    long_desc = rfc822_escape(self.get_long_description())

  File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape

    lines = header.split('\n')

TypeError: Type str doesn't support the buffer API

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-x0iek_d8/exp10it
Storing debug log for failure in /root/.pip/pip.log

**Comment by 3xp10it** [comment]
xwaf.py's code updated in line8 from:
`os.system("pip3 install exp10it -U --no-cache")`
to:
`os.system("pip3 install exp10it -U --no-cache-dir")`
you can try it again,thanks for your issue.
